[package]
name = "polkadot-service"
rust-version = "1.60"
version = "4.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "polkadot-service"

[dependencies]
sc-authority-discovery = { version = "0.31.0", path = "../../../substrate/client/authority-discovery" }
babe = { package = "sc-consensus-babe", path = "../../../substrate/client/consensus/babe", version = "0.31.0" }
beefy = { package = "sc-consensus-beefy", path = "../../../substrate/client/consensus/beefy", version = "10.0.0" }
grandpa = { package = "sc-consensus-grandpa", path = "../../../substrate/client/consensus/grandpa", version = "0.16.0" }
mmr-gadget = { version = "26.0.0", path = "../../../substrate/client/merkle-mountain-range" }
sp-mmr-primitives = { version = "23.0.0", path = "../../../substrate/primitives/merkle-mountain-range" }
sc-block-builder = { version = "0.30.0", path = "../../../substrate/client/block-builder" }
sc-chain-spec = { version = "24.0.0", path = "../../../substrate/client/chain-spec" }
sc-client-api = { version = "25.0.0", path = "../../../substrate/client/api" }
sc-client-db = { version = "0.32.0", path = "../../../substrate/client/db" }
sc-consensus = { version = "0.30.0", path = "../../../substrate/client/consensus/common" }
sc-consensus-slots = { version = "0.30.0", path = "../../../substrate/client/consensus/slots" }
sc-executor = { version = "0.29.0", path = "../../../substrate/client/executor" }
sc-network = { version = "0.31.0", path = "../../../substrate/client/network" }
sc-network-common = { version = "0.30.0", path = "../../../substrate/client/network/common" }
sc-network-sync = { version = "0.30.0", path = "../../../substrate/client/network/sync" }
sc-transaction-pool = { version = "25.0.0", path = "../../../substrate/client/transaction-pool" }
sc-transaction-pool-api = { version = "25.0.0", path = "../../../substrate/client/transaction-pool/api" }
sc-sync-state-rpc = { version = "0.31.0", path = "../../../substrate/client/sync-state-rpc" }
sc-keystore = { version = "22.0.0", path = "../../../substrate/client/keystore" }
sc-basic-authorship = { version = "0.31.0", path = "../../../substrate/client/basic-authorship" }
sc-offchain = { version = "26.0.0", path = "../../../substrate/client/offchain" }
sc-sysinfo = { version = "24.0.0", path = "../../../substrate/client/sysinfo" }
service = { package = "sc-service", path = "../../../substrate/client/service", default-features = false, version = "0.32.0" }
telemetry = { package = "sc-telemetry", path = "../../../substrate/client/telemetry", version = "12.0.0" }
sp-authority-discovery = { version = "23.0.0", path = "../../../substrate/primitives/authority-discovery" }
consensus_common = { package = "sp-consensus", path = "../../../substrate/primitives/consensus/common", version = "0.29.0" }
beefy-primitives = { package = "sp-consensus-beefy", path = "../../../substrate/primitives/consensus/beefy", version = "10.0.0" }
grandpa_primitives = { package = "sp-consensus-grandpa", path = "../../../substrate/primitives/consensus/grandpa", version = "10.0.0" }
sp-inherents = { version = "23.0.0", path = "../../../substrate/primitives/inherents" }
sp-keyring = { version = "28.0.0", path = "../../../substrate/primitives/keyring" }
sp-api = { version = "23.0.0", path = "../../../substrate/primitives/api" }
sp-block-builder = { version = "23.0.0", path = "../../../substrate/primitives/block-builder" }
sp-blockchain = { version = "25.0.0", path = "../../../substrate/primitives/blockchain" }
sp-core = { version = "25.0.0", path = "../../../substrate/primitives/core" }
sp-io = { version = "27.0.0", path = "../../../substrate/primitives/io" }
sp-keystore = { version = "0.31.0", path = "../../../substrate/primitives/keystore" }
sp-offchain = { package = "sp-offchain", path = "../../../substrate/primitives/offchain", version = "23.0.0" }
sp-runtime = { version = "28.0.0", path = "../../../substrate/primitives/runtime" }
sp-session = { version = "24.0.0", path = "../../../substrate/primitives/session" }
sp-storage = { version = "17.0.0", path = "../../../substrate/primitives/storage" }
sp-transaction-pool = { version = "23.0.0", path = "../../../substrate/primitives/transaction-pool" }
pallet-transaction-payment = { version = "25.0.0", path = "../../../substrate/frame/transaction-payment" }
sp-timestamp = { version = "23.0.0", path = "../../../substrate/primitives/timestamp" }
sp-consensus-babe = { version = "0.29.0", path = "../../../substrate/primitives/consensus/babe" }
sp-state-machine = { version = "0.32.0", path = "../../../substrate/primitives/state-machine" }
sp-weights = { version = "24.0.0", path = "../../../substrate/primitives/weights" }
sp-version = { version = "26.0.0", path = "../../../substrate/primitives/version" }
pallet-babe = { version = "25.0.0", path = "../../../substrate/frame/babe" }
pallet-im-online = { version = "24.0.0", path = "../../../substrate/frame/im-online" }
pallet-staking = { version = "25.0.0", path = "../../../substrate/frame/staking" }
pallet-transaction-payment-rpc-runtime-api = { version = "25.0.0", path = "../../../substrate/frame/transaction-payment/rpc/runtime-api" }
frame-system = { version = "25.0.0", path = "../../../substrate/frame/system" }
frame-system-rpc-runtime-api = { version = "23.0.0", path = "../../../substrate/frame/system/rpc/runtime-api" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", path = "../../../substrate/utils/prometheus", version = "0.16.0" }
frame-support = { version = "25.0.0", path = "../../../substrate/frame/support" }
frame-benchmarking-cli = { version = "29.0.0", path = "../../../substrate/utils/frame/benchmarking-cli" }
frame-benchmarking = { version = "25.0.0", path = "../../../substrate/frame/benchmarking" }

# External Crates
async-trait = "0.1.57"
futures = "0.3.21"
hex-literal = "0.4.1"
is_executable = "1.0.1"
gum = { package = "tracing-gum", path = "../gum", version = "4.0.0" }
log = "0.4.17"
schnellru = "0.2.1"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
thiserror = "1.0.48"
kvdb = "0.13.0"
kvdb-rocksdb = { version = "0.19.0", optional = true }
parity-db = { version = "0.4.8", optional = true }
codec = { package = "parity-scale-codec", version = "3.6.1" }
polkadot-core-primitives = { version = "4.0.0", path = "../../core-primitives" }
polkadot-node-core-parachains-inherent = { version = "4.0.0", path = "../core/parachains-inherent" }
polkadot-overseer = { version = "4.0.0", path = "../overseer" }
polkadot-parachain-primitives = { version = "3.0.0", path = "../../parachain" }
polkadot-primitives = { version = "4.0.0", path = "../../primitives" }
polkadot-node-primitives = { version = "4.0.0", path = "../primitives" }
polkadot-rpc = { version = "4.0.0", path = "../../rpc" }
polkadot-node-subsystem = { version = "4.0.0", path = "../subsystem" }
polkadot-node-subsystem-util = { version = "4.0.0", path = "../subsystem-util" }
polkadot-node-subsystem-types = { version = "4.0.0", path = "../subsystem-types" }
polkadot-runtime-parachains = { version = "4.0.0", path = "../../runtime/parachains" }
polkadot-node-network-protocol = { version = "4.0.0", path = "../network/protocol" }

# Polkadot Runtime Constants
rococo-runtime-constants = { path = "../../runtime/rococo/constants", optional = true, version = "4.0.0" }
westend-runtime-constants = { path = "../../runtime/westend/constants", optional = true, version = "4.0.0" }

# Polkadot Runtimes
westend-runtime = { path = "../../runtime/westend", optional = true, version = "4.0.0" }
rococo-runtime = { path = "../../runtime/rococo", optional = true, version = "4.0.0" }

# Polkadot Subsystems
polkadot-approval-distribution = { path = "../network/approval-distribution", optional = true, version = "4.0.0" }
polkadot-availability-bitfield-distribution = { path = "../network/bitfield-distribution", optional = true, version = "4.0.0" }
polkadot-availability-distribution = { path = "../network/availability-distribution", optional = true, version = "4.0.0" }
polkadot-availability-recovery = { path = "../network/availability-recovery", optional = true, version = "4.0.0" }
polkadot-collator-protocol = { path = "../network/collator-protocol", optional = true, version = "4.0.0" }
polkadot-dispute-distribution = { path = "../network/dispute-distribution", optional = true, version = "4.0.0" }
polkadot-gossip-support = { path = "../network/gossip-support", optional = true, version = "4.0.0" }
polkadot-network-bridge = { path = "../network/bridge", optional = true, version = "4.0.0" }
polkadot-node-collation-generation = { path = "../collation-generation", optional = true, version = "4.0.0" }
polkadot-node-core-approval-voting = { path = "../core/approval-voting", optional = true, version = "4.0.0" }
polkadot-node-core-av-store = { path = "../core/av-store", optional = true, version = "4.0.0" }
polkadot-node-core-backing = { path = "../core/backing", optional = true, version = "4.0.0" }
polkadot-node-core-bitfield-signing = { path = "../core/bitfield-signing", optional = true, version = "4.0.0" }
polkadot-node-core-candidate-validation = { path = "../core/candidate-validation", optional = true, version = "4.0.0" }
polkadot-node-core-chain-api = { path = "../core/chain-api", optional = true, version = "4.0.0" }
polkadot-node-core-chain-selection = { path = "../core/chain-selection", optional = true, version = "4.0.0" }
polkadot-node-core-dispute-coordinator = { path = "../core/dispute-coordinator", optional = true, version = "4.0.0" }
polkadot-node-core-prospective-parachains = { path = "../core/prospective-parachains", optional = true, version = "3.0.0" }
polkadot-node-core-provisioner = { path = "../core/provisioner", optional = true, version = "4.0.0" }
polkadot-node-core-pvf = { path = "../core/pvf", optional = true, version = "4.0.0" }
polkadot-node-core-pvf-checker = { path = "../core/pvf-checker", optional = true, version = "4.0.0" }
polkadot-node-core-runtime-api = { path = "../core/runtime-api", optional = true, version = "4.0.0" }
polkadot-statement-distribution = { path = "../network/statement-distribution", optional = true, version = "4.0.0" }

xcm = { package = "staging-xcm", path = "../../xcm", default-features = false, version = "4.0.0" }
xcm-builder = { package = "staging-xcm-builder", path = "../../xcm/xcm-builder", default-features = false, version = "4.0.0" }
xcm-payment-runtime-api = { package = "xcm-payment-runtime-api", path = "../../xcm/xcm-builder/xcm-payment-runtime-api", default-features = false, version = "0.0.1" }

[dev-dependencies]
polkadot-test-client = { path = "../test/client" }
polkadot-node-subsystem-test-helpers = { path = "../subsystem-test-helpers" }
env_logger = "0.9.0"
assert_matches = "1.5.0"
serial_test = "2.0.0"
tempfile = "3.2"

[features]
default = ["db", "full-node"]

db = ["service/rocksdb"]

full-node = [
	"kvdb-rocksdb",
	"parity-db",
	"polkadot-approval-distribution",
	"polkadot-availability-bitfield-distribution",
	"polkadot-availability-distribution",
	"polkadot-availability-recovery",
	"polkadot-collator-protocol",
	"polkadot-dispute-distribution",
	"polkadot-gossip-support",
	"polkadot-network-bridge",
	"polkadot-node-collation-generation",
	"polkadot-node-core-approval-voting",
	"polkadot-node-core-av-store",
	"polkadot-node-core-backing",
	"polkadot-node-core-bitfield-signing",
	"polkadot-node-core-candidate-validation",
	"polkadot-node-core-chain-api",
	"polkadot-node-core-chain-selection",
	"polkadot-node-core-dispute-coordinator",
	"polkadot-node-core-prospective-parachains",
	"polkadot-node-core-provisioner",
	"polkadot-node-core-pvf",
	"polkadot-node-core-pvf-checker",
	"polkadot-node-core-runtime-api",
	"polkadot-statement-distribution",
]

# Configure the native runtimes to use.
westend-native = ["westend-runtime", "westend-runtime-constants"]
rococo-native = ["rococo-runtime", "rococo-runtime-constants"]

runtime-benchmarks = [
	"frame-benchmarking-cli/runtime-benchmarks",
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-babe/runtime-benchmarks",
	"pallet-im-online/runtime-benchmarks",
	"pallet-staking/runtime-benchmarks",
	"polkadot-parachain-primitives/runtime-benchmarks",
	"polkadot-primitives/runtime-benchmarks",
	"polkadot-runtime-parachains/runtime-benchmarks",
	"rococo-runtime?/runtime-benchmarks",
	"sc-client-db/runtime-benchmarks",
	"service/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"westend-runtime?/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-babe/try-runtime",
	"pallet-im-online/try-runtime",
	"pallet-staking/try-runtime",
	"pallet-transaction-payment/try-runtime",
	"polkadot-runtime-parachains/try-runtime",
	"rococo-runtime?/try-runtime",
	"sp-runtime/try-runtime",
	"westend-runtime?/try-runtime",
]
fast-runtime = ["rococo-runtime?/fast-runtime", "westend-runtime?/fast-runtime"]

malus = ["full-node"]
runtime-metrics = [
	"polkadot-runtime-parachains/runtime-metrics",
	"rococo-runtime?/runtime-metrics",
	"westend-runtime?/runtime-metrics",
]
